### ISSUE TITLE
cannot compile libpll

### ISSUE THREAD

**Issue by svicario** [Pbdas/epa-ng#10]
When I type in the epa folder "make pll" to start installation 
I got 
mkdir -p bin
cd libs/pll-modules && ./install-with-libpll.sh .. 
/bin/sh: 1: ./install-with-libpll.sh: not found
and indeed I cannot find anywhere the file  install-with-libpll.sh

**Comment by Pbdas** [comment]
Hi svicario! 
Are you sure you cloned the repository using the `--recursive` flag? If not, you can fix this by running
```git submodule update --init --recursive``` in the `epa-ng` folder.

**Comment by svicario** [comment]
indeed I downloaded the zip. I will get from git

**Comment by svicario** [comment]
compiled and tested with demo file: all okay
