### ISSUE TITLE
unimplemented pure virtual method error

### ISSUE THREAD

**Issue by gavinmdouglas** [Pbdas/epa-ng#18]
Hi there,

I've been troubleshooting whether EPA-NG could be installed with conda and I've been running into this error when trying to install with clang rather than gcc (first reported [here](https://github.com/bioconda/bioconda-recipes/issues/11617)):

> /Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/build/genesis_unity_sources/lib/all.cpp:17912:56: error: allocating an object of abstract class type 'const utils::ColorNormalization'
>         tree, params, std::vector<utils::Color>{}, {}, {}, svg_filename
>                                                        ^
> /Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/libs/genesis/lib/genesis/utils/tools/color/normalization.hpp:168:20: note: unimplemented pure virtual method 'normalize_' in 'ColorNormalization'
>     virtual double normalize_( double value ) const = 0;
>                    ^
> /Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/libs/genesis/lib/genesis/utils/tools/color/normalization.hpp:173:18: note: unimplemented pure virtual method 'is_valid_' in 'ColorNormalization'
>     virtual bool is_valid_() const = 0;
>                  ^
> /Users/distiller/project/miniconda/conda-bld/epa-ng_1540400737097/work/build/genesis_unity_sources/lib/all.cpp:17923:45: error: allocating an object of abstract class type 'const utils::ColorNormalization'
>         tree, params, color_per_branch, {}, {}, svg_filename

I know EPA-NG hasn't been tested on Mac OS X (which uses clang), but from what I understand this may actually be a bug that wasn't caught by gcc. This is based on the development version forked on Sep 5, 2018 (commit: 45a8e536e6af3ac4119290eeafcc756aa8b8c5c8). Please let me know if you would like more details!

Gavin

**Comment by lczech** [comment]
Hi @gavinmdouglas,

I am the developer of the genesis library that EPA-ng is using. Thanks for catching that bug! It is a bit weird though, because genesis is also tested with clang, and this issue is something that should have popped up earlier... Can you please tell me which clang version you used exactly?

Anyway, the problem was in a small helper function that was totally unrelated to EPA-ng, so nothing to worry about. It is fixed now in genesis, so now EPA-ng needs to update to the latest genesis version, and then everything should work fine!

Lucas

**Comment by lczech** [comment]
Update from the bioconda issue. The report of building EPA-ng on Mac OS revealed some issues:

 * Will have to fix the CMake OpenMP package finding (probably using my genesis patch will work fine).
 * Might need to have a look into PLL modules shared library setup, as newer CMake versions seem to complain about that. 
 * Furthermore, PLL seems to have some uninitialized variables, which is smelly.

**Comment by gavinmdouglas** [comment]
Hi @Pbdas ,

Thanks for your fast response and fixes! I'll keep you updated on the conda package.


Best,

Gavin
