### ISSUE TITLE
src/core/pll/pll_util.cpp compile error: ‘tie’ is not a member of ‘std’ 

### ISSUE THREAD

**Issue by balabanmetin** [Pbdas/epa-ng#21]
I was getting this compile error. Adding `#include <tuple>` on `/src/core/pll/pll_util.cpp` fixes the issue.
Edit: I am using gcc 4.9.2 compiler.

**Comment by lczech** [comment]
Thanks, we also already found this bug and it should be fixed in the current master branch (which is only this commit ahead of the latest release). Please try this version and let us know if that works for you!
