### ISSUE TITLE
Segmentation fault when processing a large number of sequences

### ISSUE THREAD

**Issue by apcamargo** [Pbdas/epa-ng#24]
I'm trying to use the latest version EPA-ng to process ~5,000 sequences but I get a `Segmentation fault (core dumped)` after 3500 sequences. I don't get this issue in version `0.2.1-beta`.

**Comment by Pbdas** [comment]
Hi @apcamargo,
would it be possible for you to share the input data with me?

**Comment by heuklang** [comment]
Hi @Pbdas 
I has same issue. Could I share input data with you?

**Comment by apcamargo** [comment]
@Pbdas I don't own the data that gave me the issue, so I can't share it. In any case, it seems that @heuklang can help you with that

**Comment by Pbdas** [comment]
@heuklang that would be great, please contact me: pierre.barbera at h-its.org

**Comment by Pbdas** [comment]
ok so far it looks like the issue only occurs when using `.bfast` as input files, though it doesn't occur with all such data.

So a workaround for 0.3.4 is to just input the aligned query sequences as either `.fasta` or `.fasta.gz`. Coincidentally, as I understand, that is how the newer versions of picrust2 handles it :)

**Comment by heuklang** [comment]
[https://github.com/picrust/picrust2/pull/53#issue-248172753](url)

**Comment by heuklang** [comment]
[issue related link](https://github.com/picrust/picrust2/pull/53)

**Comment by Pbdas** [comment]
The issue was indeed a bug with genesis. A bug that only happened for files between 4 and 8 MB! Pushing a fix now.
