### ISSUE TITLE
Internal node labels disappear from reference tree

### ISSUE THREAD

**Issue by aaronmussig** [Pbdas/epa-ng#26]
Hi,

It appears that the internal node labels from the reference tree are not present in the output file. Is there an option to preserve these labels?

Thanks.

**Comment by Pbdas** [comment]
Hi @aaronmussig,
the latest commit on the dev branch now preserves inner node labels. Let me know if it works for you!

Happy Placement,
Pierre

**Comment by aaronmussig** [comment]
Hi Pierre,

Thanks so much for a quick reply and implementation into dev. I have had the chance to compile and run it today and it works very well. 

I did find in my case though, that the node labels require single quotes in the json file to be compatible with guppy tog, e.g.

Output from dev:
```
(GB_GCA_001657325.1:0.0646094670{17277},RS_GCF_000332355.1:0.0527523200{17278})0.999:g__Geitlerinema:0.0254640410{17279})1.0:0.0734447620{17280},RS_GCF_001870905.1:0.1785309470{17281})0.991:f__Geitlerinemaceae:0.0262647820{17282})0.913:0.0164857460{17283},(RS_GCF_001746915.1:0.1034793530{17284},(GB_GCA_002340255.1:0.0079385140{17285},GB_GCA_001890975.1:0.0058043340{17286})1.0:g__Roseofilum:0.1388184350{17287})1.0:f__Desertifilaceae:0.0484466950{17288}):0.0107564550{17289})0.996:o__Cyanobacteriales:0.0213733420{17290},(((RS_GCF_001939115.1:0.1172539000{17291},RS_GCF_000775285.1:0.1336094850{17292})o__Neosynechococcales;f__Neosynechococcaceae:0.0122746680{17293},RS_GCF_000317045.1:0.1267942170{17294}):0.0093001140{17295},((((RS_GCF_000332095.2:0.1346119830{17296}, ....
```

Expected output:
```
(GB_GCA_001657325.1:0.0646094670{17277},RS_GCF_000332355.1:0.0527523200{17278})'0.999:g__Geitlerinema':0.0254640410{17279})1.0:0.0734447620{17280},RS_GCF_001870905.1:0.1785309470{17281})'0.991:f__Geitlerinemaceae':0.0262647820{17282})0.913:0.0164857460{17283},(RS_GCF_001746915.1:0.1034793530{17284},(GB_GCA_002340255.1:0.0079385140{17285},GB_GCA_001890975.1:0.0058043340{17286})'1.0:g__Roseofilum':0.1388184350{17287})'1.0:f__Desertifilaceae':0.0484466950{17288}):0.0107564550{17289})'0.996:o__Cyanobacteriales':0.0213733420{17290},(((RS_GCF_001939115.1:0.1172539000{17291},RS_GCF_000775285.1:0.1336094850{17292})'o__Neosynechococcales;f__Neosynechococcaceae':0.0122746680{17293},RS_GCF_000317045.1:0.1267942170{17294}):0.0093001140{17295},((((RS_GCF_000332095.2:0.1346119830{17296}, ....
```

I surrounded anything matching ```((?:\d+\.\d+:)?\w__[\w\d-\;]*)``` in the output with single quotes to test if the preservation of node label works as expected, and it did. Once again, thanks for your time.

Aaron

**Comment by Pbdas** [comment]
Hi Aaron,

I'm guessing the `1.0:some_label` are branch support values? Also I noticed there being a semicolon in a label, which would definitely cause issues in a newick string.

I'll have the final version escape such problematic labels using single quotes, but personally I'd opt for avoiding characters with special meaning in newick, since you never know if some other downstream program can handle it or not. Plus it saves you from un-extracting the labels from the single quotes afterwards...

Best,
Pierre

**Comment by lczech** [comment]
Hi @aaronmussig,

I'd like to add that the usage of single `'` and double `"` quotation marks is an interpretation/extension of the Newick format - which is not standardized in any way anyway, so it's a mess... See e.g., [this description](http://wiki.christophchamp.com/index.php?title=Newick_phylogenetic_tree_format). Hence, I'd recommend reading [our paper on issued with the Newick format](https://academic.oup.com/mbe/article/34/6/1535/3077051).

Lastly, you might also want to have a look at our program gappa, which re-implements some of the functions of guppy, and might offer some more options (and definitely more speed) than guppy. For example, the `tog` command of guppy is called `graft` in gappa, [see here](https://github.com/lczech/gappa/wiki/Subcommand:-graft).

Let me know if this was helpful. Best
Lucas

**Comment by aaronmussig** [comment]
Excellent, thanks @lczech I'll have a look into it.
