### ISSUE TITLE
epa-ng available on Homebrew through brewsci/bio

### ISSUE THREAD

**Issue by gaberoo** [Pbdas/epa-ng#27]
Hi,

I just wanted to let you know that we've put together a Homebrew formula for epa-ng that's available through the brewsci/bio tap. Just in case you wanted to list this on the README.

```
brew tap brewsci/bio
brew install epa-ng
```
or
```
brew install brewsci/bio/epa-ng
```

Cheers,
Gabriel

**Comment by Pbdas** [comment]
Hi Gabriel,

very cool, this is highly appreciated!

When a new version is released, does the formula get updated automatically?

Pierre

**Comment by gaberoo** [comment]
Hi Pierre,

Unfortunately not as far as I know. Though I have turned on notifications when new releases are deployed.
