### ISSUE TITLE
-INF logl at branch 0 error

### ISSUE THREAD

**Issue by Saellenee** [Pbdas/epa-ng#34]
Hello,

It is my first time reporting an issue on github so I'm sorry if I'm not the clearest.

I've been using epa-ng v0.3.5 for phylogenetic placement with no problems so far, but recently I'm stuck with an error.

This is the code line I wrote (I changed the name to make it more clear) :
epa-ng --model GTR{1.08637/3.57995/1.86164/0.81671/6.21607/1.00000}+FU{0.235/0.257/0.328/0.179}+IU{0.014}+G4{0.639} --ref-msa reference-seq.ali --tree reference-tree.treefile --query query.ali --outdir EPA-ng-Jplacer --redo

The return I got is:
```
INFO Selected: Output dir: EPA-ng-Jplacer/
INFO Selected: Query file: query.ali
INFO Selected: Tree file: reference-tree.treefile
INFO Selected: Reference MSA: reference-seq.ali 
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model: GTR{1.08637/3.57995/1.86164/0.81671/6.21607/1.00000}+FU{0.235/0.257/0.328/0.179}+IU{0.014}+G4{0.639}
INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 0.639 (user),  weights&rates: (0.25,0.0612386) (0.25,0.333269) (0.25,0.899982) (0.25,2.70551) 
        P-inv (user): 0.014
        Base frequencies (user): 0.235235 0.257257 0.328328 0.179179 
        Substitution rates (user): 1.08637 3.57995 1.86164 0.81671 6.21607 1
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.5)
INFO Output file: EPA-ng_Jplacer_Article3_cleaned4/epa_result.jplace
srun: error: Amoeba-mt6: task 0: Aborted
task 0: Aborted

And if I look at the log file I get :
terminate called after throwing an instance of 'std::runtime_error'
what():  -INF logl at branch 0 with sequence QUERY_DALLOL_1339_Gt_7Gt_7Gt-pp_Ass
```

Which honestly I don't understand what it means and I didn't see anybody report the same problem.

I probably did a dumb mistake somewhere but honestly I don't have a clue of what it is. Can you please help me ?

What I tried already :
- The sequence signaled is the 1st one of my file so I tried to remove it. The same issue appear with the next sequence. So that's not the problem of the sequence.
- Try to use EPA-ng with other files : works OK (but the reference tree has less OTUs. For this one it's 2993 OTUs only for the reference sequences)
- Reduce the number of my query from 1634 to 10 to see if it was a query number problem : same issue.
- Reroot my tree : same issue.
- Run EPA-ng with different number of threads : same issue.
- Check for hidden caracters : didn't detect any
- Redo everything and check files (the tree is in Newick format from IQTree) : didn't change anything

Hope I was clear and that there's a solution to this issue
Thanks for reading / your help
JB

**Comment by Pbdas** [comment]
Hi @Saellenee,
please update to the newest version and try again. If you used `git` you can do the following:

```
git pull
git submodules update --init --recursive
make clean
make
```

Let me know if the issue persists!

Pierre

**Comment by Saellenee** [comment]
Thanks Pierre for your reply,

The new version gave me a clearer error message and I could find right away what the problem was. There was actually a problem in one of the reference sequence name in the alignment file (a special caracter) that I missed. IQTree ignored it and replaced it by a "_" so I didn't have issue running the reference tree and didn't realize. I focused too much on the query file and missed that.

Thank you very much, I can continue peacefuly now !

Have a great day,

JB

**Comment by Pbdas** [comment]
great to hear! Let me know if you run into any futher issues :)

Happy Placement!
Pierre
