### ISSUE TITLE
PLL assertion error

### ISSUE THREAD

**Issue by cmorganl** [Pbdas/epa-ng#35]
Hi Pierre,

I'm placing some sequences onto a relatively small tree with EPA-NG v0.3.7 and it's aborting after a failed assertion in PLL:
```
epa-ng: /home/connor/bin/epa-ng/libs/pll-modules/libs/libpll/src/core_likelihood_avx2.c:911: pll_core_edge_loglikelihood_repeats_generic_avx2: Assertion `site_lk < 0. && isfinite(site_lk)' failed.
Aborted (core dumped)
```

Here is the command I used:
`epa-ng -s references.txt -t NosZ.txt -q queries.txt --model NosZ_epa.model.txt --dyn-heur 0.9 -T 4 --no-pre-mask`

Placement is completed if I allow masking by removing '--no-pre-mask'.

Files used:
[NosZ.txt](https://github.com/Pbdas/epa-ng/files/5221116/NosZ.txt)
[NosZ_epa.model.txt](https://github.com/Pbdas/epa-ng/files/5221118/NosZ_epa.model.txt)
[queries.txt](https://github.com/Pbdas/epa-ng/files/5221119/queries.txt)
[references.txt](https://github.com/Pbdas/epa-ng/files/5221120/references.txt)

Can you figure out what is wrong?

Thanks!
Connor

**Comment by Pbdas** [comment]
Hi Connor,

I can't reproduce the error, are you sure you're really on 0.3.7 or above? If you updated it via `git pull`, make sure you also update the submodules correctly:
```
git submodule update --init --recursive
make clean
make -j4
```

Pierre

**Comment by cmorganl** [comment]
Hi Pierre,

I did have EPA-NG v0.3.7 installed but the issue was fixed by updating the submodules as you suggested.

Thanks for your help!

**Comment by Pbdas** [comment]
No problem, thanks for reaching out, and let us know if you need any more help or advice :)
