### ISSUE TITLE
error when doing the final epa-ng placement

### ISSUE THREAD

**Issue by AnaMariaCabello** [Pbdas/epa-ng#40]
Hi!
I got this error when running:
epa-ng
    -t reference_tree.raxml.bestTree
    -s reference_aligment.fasta
    -q query.fasta
    -w ./ --model reference_tree.raxml.bestModel

Please find attached the .err and the info.log files
[jobLog_447616.err.txt](https://github.com/Pbdas/epa-ng/files/7587753/jobLog_447616.err.txt)
[epa_info.log.txt](https://github.com/Pbdas/epa-ng/files/7587754/epa_info.log.txt)

It looks like the query.fasta produces after ena-ng --split has a problem, but it looks normal to me.

Thank you so much for your help.

**Comment by Pbdas** [comment]
Hi @AnaMariaCabello !

looks like you're on an older version of epa-ng (0.3.5), could you try again with the current version?

Pierre

**Comment by AnaMariaCabello** [comment]
oK! I will try that.
which one is the current version?

Thank you so much Pierre

**Comment by Pbdas** [comment]
That would be v0.3.8. How did you install the program?

**Comment by AnaMariaCabello** [comment]
I didn't install it myself, it's installed in a cluster.

**Comment by Pbdas** [comment]
Hi @AnaMariaCabello, have you been able to update the version yet? Alternatively you can install the program locally for your user, following the instructions in the readme in this repository. let me know if you need any help.

**Comment by AnaMariaCabello** [comment]
Hi Pierre!
not yet, I’m waiting for the cluster tech to uodate the version.
I’ll let you know how it goes as soon as I try again.

Thanks,
Ana

**Comment by AnaMariaCabello** [comment]
Hi Pierre,
I finally tried to do a placement of short sequences (ca. 400 bps, a total of 39 sequences ) to a reference tree (24 reference sequences, ca. 1800 bps) using version v0.3.8.
The papara alignment worked and the epa-ng seemed to work too, but the epa_result.jplace output after running the epa-ng command did not include the short sequences, so I obtained only the sequences in the reference tree (I used itol to visualize the epa_result.jplace tree). 

Is there any further step needed? 

please find attached the commands and the .out files for both. 
The error file for epa-ng was empty and the error file for papara only contained this:
sweep: 138 -> 0
[commands_placeme
[epang_jobLog_458414.out.txt](https://github.com/Pbdas/epa-ng/files/7888559/epang_jobLog_458414.out.txt)
nt.txt](https://github.com/Pbdas/epa-ng/files/7888550/commands_placement.txt)
[papara_jobLog_458409.out.txt](https://github.com/Pbdas/epa-ng/files/7888576/papara_jobLog_458409.out.txt)

Thanks a lot!
Ana

**Comment by AnaMariaCabello** [comment]
Dear Pierre,
You were right, that was the mixup. Is there a way to visualise the placements as a new branches in the reference tree? this is my goal, but maybe I should have used a different approach. Should I use instead guppy or pplacer?  could I use as input file for this the output of epa-ng, so the epa_result.jplace file? Any guidance on this will be appreciated. 
Thank you so much,
Ana

**Comment by Pbdas** [comment]
Dear Ana,

you can generate such a tree using our other software called [gappa](https://github.com/lczech/gappa), which includes a whole host of post-analysis methods that operate on phylogenetic placement results (in the form of .jplace files). The command you are looking for is called [graft](https://github.com/lczech/gappa/wiki/Subcommand:-graft). This will generate a newick file with the queries mixed in.

Let us know if you run into any other issues!
Pierre

**Comment by AnaMariaCabello** [comment]
OK, great! Thank you so much!
