### ISSUE TITLE
Treeparsing error 

### ISSUE THREAD

**Issue by csanchis** [Pbdas/epa-ng#42]
Hello, I'm tryting to run epa-ng with a newick tree generated with ETE3 (previously resolving the polytomies) and I recieve this error: 

terminate called after throwing an instance of 'std::runtime_error'
  what():  Treeparsing failed! syntax error, unexpected $end, expecting ','. (line 1 column 55)

I have checked several times the newick format, and I don't understand why is reading an "end" in the middle of the tree...
Could you guide me for solving this problem, please?

Thank you very much in advance

**Comment by Pbdas** [comment]
Hi @csanchis!

some things to check for: 
- make sure you don't have any newick-related special characters in your taxa labels (could there by a semicolon at the 55th character in the newick string?)
- make sure the tree is actually fully resolved (which should be the case as you mentioned)
- which version of EPA-ng are you using?

If you like, you can post the tree here so I can have a look.

Pierre

**Comment by csanchis** [comment]
Hi again, thanks for answering so quickly.

I revised the semicolon characters, and it only appears once, at the end. 
I did the resolving step with ETE3 because previously I had a different error given the polytomies in the tree.
My version is: EPA-ng v0.3.8

I attach the tree file: 
https://drive.google.com/file/d/1qrLxqXhhe_PdgCMr7SZsjZWLC2zJK1b3/view?usp=sharing


Thank you.

**Comment by Pbdas** [comment]
Dear Claudia,

unfortunately EPA-ng doesn't yet support newick trees that contain NHX (New Hampshire eXtended) strings. Do you think it would be useful to have, i.e. for co-visualizing placements and support values/other custom labels? Perhaps the visualisation would become too busy?

Either way, for now you can remove the NHX labels like this in the terminal:
```
sed -e 's/\[[^][]*\]//g' COG0012.nw > COG_no_NHX.nw
```
and try again. Quick warning however, your tree seems to be on the larger side. Depending on the width of your alignment, you can expect a large memory footprint.

By the way, as these kind of questions come up semi-regularly, it has inspired @lczech to write a command for lczech/gappa that sanity-checks/cleans reference trees such that they work with EPA-ng afterwards :)

Happy Placement (and let me know if you run into more trouble!),
Pierre

**Comment by lczech** [comment]
Hi @csanchis,

as @Pbdas mentioned, this thread finally led me to implement a command to remove Newick extensions from files that some tools have trouble with. If you do not need these data, you can use the `clean-tree` command available in [gappa v0.8.1](https://github.com/lczech/gappa/releases/tag/v0.8.1) to clean your file. In your case, the annotations are of the form `[&&NHX:support=1.0]` and `[&&NHX:name=0.997]`, which probably come from the tool that you used to infer the tree. They are not needed for conducting phylogenetic placement with epa-ng.

Cheers, let me know if this works for you, and so long
Lucas

**Comment by csanchis** [comment]
Thank you both for your answers @Pbdas @lczech 

I have it working now, I finally removed the annotations so the problem is solved. 

Thank you for your time,
Claudia

**Comment by lczech** [comment]
Awesome, closing the issue then. Re-open if needed, or start another issue if you have any more trouble (hopefully not)!
