### ISSUE TITLE
How to convert the epa results (jplace) to the newick format?

### ISSUE THREAD

**Issue by Bin-Ma** [Pbdas/epa-ng#46]
@stamatak  I want to compare the placement with the reference tree. But I have no idea about how to convert the format to the newick? Looking forward to your reply!

**Comment by lczech** [comment]
Dear @Bin-Ma,

the gappa graft command can do that, see here: https://github.com/lczech/gappa/wiki/Subcommand:-graft

However, you should first read up on how to interpret that - as this is not a simple conversion. Phylogenetic Placement contains uncertainty of the placements, which is lost when turning the data into a Newick tree.

I'd recommend reading our review article for more information:

> Metagenomic Analysis Using Phylogenetic Placement—A Review of the First Decade.
> Lucas Czech, Alexandros Stamatakis, Micah Dunthorn, and Pierre Barbera.
> Frontiers in Bioinformatics, 2022. https://doi.org/10.3389/fbinf.2022.871393

Hope that helps :-)
Closing the issue now, but feel free to re-open should you have more questions!

Lucas

**Comment by lczech** [comment]
PS: Should you have more questions, you can also check out our google group: https://groups.google.com/forum/#!forum/phylogenetic-placement - which is the preferred place for questions like this.

**Comment by Bin-Ma** [comment]
Thanks for your reply. I will try it right now! @lczech
