### ISSUE TITLE
Help on Aborted (core dumped) message

### ISSUE THREAD

**Issue by pterzian** [Pbdas/epa-ng#48]
Hi,

Similar to a recent post, I am trying to do placement for 1.3k sequences msa file builded with mafft. I first build a conda env with raxml & epa-ng. 

I then checked my msa file with --parse & --check commands form raxml-ng, it suggested I would need 7 threads for 1200MB mem. I have around 200GB available so I don't really understand why I would have unsuficient ressources.

This is my current command line (I also used iqtree web server to find the best model and parameters).

```
epa-ng --ref-msa $refmsa --tree $reftree --query $querymsa -w . --threads 7 --chunk-size 500 --model GTR+F+I+G4
```
I don't have any error printed but the `Aborted (core dumped)` message.

Any suggestions that could help me ?

Edit : 

* Used pythia on my query sequences and obtained a 0.63 difficulty.

* Not really the place for it but since I posted I also tried pplacer and also got the same aborted error but with a complementary message I don't understand yet (I am very new to phylogenetic placement) :

```
pplacer: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
```
* Tried the test data, it worked for 10k sequences but failed for 100k returning the same Aborted (core dumped) message. **Edit** : It worked for 100k seq after adding the `--redo` option for some reason.

* Actually trying to reduces number of queries, deduplicating reference sequences and other strategies I could found but so far I am stucked on the same issue. 

**some unanswered questions I have so far**

* I red "Many placement methods require query reads to be aligned to the reference". I am not sure I understand this step. I also found this information in this tutorial [here](https://www.polarmicrobes.org/phylogenetic-placement-re-re-visited/). Does it mean I should pre align the queries on the reference .aln before calling epa-ng ? I also found some workflow computing the alignement of queries on the hmm profile of the reference sequences but I feel I am missing something here...

* Following this last point, I generated a hmm profile from the deduplicated reference msa file, then hmmalign my queries with this hmm align with the `--mapali` options. Then extracted two msa files, one with queries only and one with references only. Got the same error again. I am starting to think the issue comes from my reference tree (is 1.3k sequences too big ?)

thxx,
Paul

**Comment by pterzian** [comment]
So I finally got to complete the phylogenetic placement with epa-ng on my dataset.

The `--redo` parameter unlocked it by printing me an error message I could do something with :
```
ERR  The reference and query alignment files do not seem to have the same alignment width! (2670 vs. 1289). Are the query sequences not aligned?
Aborting with a failure.``
```
From here I switched to my last dataset where I aligned my queries on my (deduplicated) reference sequences through a hmm model with `hmmalign`.

One particular thing that could cause the issue I had was to give directly the parameters to the `--model` option such as this :

```
--model GTR{1.0290/2.9073/1.3524/0.8292/4.8575/1.0000}+F{0.2684/0.198/0.2563/0.2774}+I{0.0245}+G4{0.6232}
```
I had found these value in the results of IQ-tree, but it never worked. Simply passing the file output of IQ-tree worked.  

The placement took `11s` to complete with 2 threads. Not sure if it comes from my install, but the software behavior to my numerous (bad) tries felt odd since I needed this `--redo` parameter to print the correct error message.

Closing this post as my original issue is solved.

**Comment by danchurch** [comment]
This was really helpful. The `--redo` flag causes my epa-ng command to work properly, with expected results, for some reason that I cannot understand. 

Without including this flag, I receive the same core-dump warning, with no information about the error.
