### ISSUE TITLE
question on comparison with RAxML-epa

### ISSUE THREAD

**Issue by jianshu93** [Pbdas/epa-ng#51]
hello Team,

I can use epa algorithm in RAxML like this:

mafft --addfragments ${name}_NarG_all.faa --reorder --thread 64 NarG.ref.afa  > ${name}_Refs_NarG_reads.aln

raxmlHPC-PTHREADS-AVX2 -f v -s ${name}_Refs_NarG_reads.aln -t RAxML_bestTree.NarG_ref_tree  -m PROTGAMMAAUTO -n ${name}_JPlace_narG -T 64 –G 0.2

That is to first add short query sequences (${name}_NarG_all.faa) to the reference alignment (NarG.ref.afa, long one to generate the backbone tree). Then run the whole alignment including short query sequences (${name}_Refs_NarG_reads.aln) with the tree generated from NarG.ref.afa (RAxML_bestTree.NarG_ref_tree). How can do this in epa-ng? since query MSA files is needed, I assume it is the reads alignment file (no reference included). Since  reads are very short and most of the tims no overlap. How do I generate a query alignment?

Thanks,

Jianshu

**Comment by lczech** [comment]
Hi @jianshu93,

please see the [wiki](https://github.com/pierrebarbera/epa-ng/wiki/Full-Stack-Example) for a full stack example. I think that should answer your question - if not, please let us know how your use case differs from what is described there :-)

Cheers and so long
Lucas

**Comment by jianshu93** [comment]
Hello Lucas,

It seems papara only supports nt, not amino acid sequence but I hav amino acid sequences and reference alignment. How do I proceed?

Thanks,

Jianshu

**Comment by lczech** [comment]
Hi Jianshu,

ah okay, hm yes, not many people seem to do placement with amino acid data... I'm not sure but maybe the hmmalign command of HMMER might be able to do that? It's the alternative alignment tool that is specialized for short queries. See also our review https://doi.org/10.3389/fbinf.2022.871393 for some more inspiration. If neither of those options work, you might need to convert to nt, or something. Not ideal, but might work.

Hope that helps, so long
Lucas

**Comment by jianshu93** [comment]
Hello Lucas,
pplacer does support aa replacement, but similar input format with epa-ng. I have a combined MSA (ref msa + query msa, obtained via mafft -- addfragments) and ref MSA alone, how do I split them into separate query MSA and ref MSA:

--split TEXT:FILE ...       Takes a reference MSA (phylip/fasta/fasta.gz) and combined ref + query MSA(s) (phylip/fasta/fasta.gz) and outputs a monolithic query file (fasta), as well as a reference file (fasta), ready for use. Usage: epa-ng --split ref_alignment query_alignments+

I am confused about this option. which one should be the combined msa to split. I did not see the option to split amino acid MSA, it is supported now?

Thanks,

Jianshu

**Comment by jianshu93** [comment]
I have a reference alignment msa (in phylip format, amino acid), tree from this msa, a query fasta (amino acid), I want to ran the PaPaRa:

papara -t RAxML_bestTree.NarG_ref_tree -s NarG.ref.rename.aligned.phylip -q Station38_NarG_all.faa -a -j 24 -r -n Station38_NarG_papara
papara called as:
papara -t RAxML_bestTree.NarG_ref_tree -s NarG.ref.rename.aligned.phylip -q Station38_NarG_all.faa -a -j 24 -r -n Station38_NarG_papara 
terminate called after throwing an instance of 'std::runtime_error'
  what():  early end of (interleaved) phylip file.
Aborted

phylip format msa was generated by muscle v3.8.1551. tree was from RAxML:

raxmlHPC-PTHREADS-AVX2 -f a -n NarG_ref_tree -o sequence_681 -s  NarG.ref.rename.aligned.phylip -m PROTGAMMAWAG -T 24 -x 1234 -p 1234 -N 2

[PaPaRa_input.zip](https://github.com/pierrebarbera/epa-ng/files/12727487/PaPaRa_input.zip)


No idea what happened. Should be a PaPaRa problem. I also attached the original reference sequence.



Thanks,
[NarG.ref.rename.fasta.zip](https://github.com/pierrebarbera/epa-ng/files/12727610/NarG.ref.rename.fasta.zip)


Thanks,
Jianshu
